services:
  web:
    build: .
    ports:
      - "5173:5173"
    env_file:
      - .env.local
    depends_on:
      - db
    volumes:
      - ".:/app"

  db:
    image: postgres:15
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
